services:
  demo:
  kml:
  tms:
  wms:
    md:
      title: MapProxy WMS Proxy
      abstract: This is the fantastic MapProxy.
      online_resource: http://mapproxy.org/

layers:
  - name: my_layer
    title: WMS layer from tiles
    sources: [mycache]

caches:
  mycache:
    disable_storage: true
    grids: [tile_grid_of_source]
    sources: [my_tile_source]

sources:
  my_tile_source:
    type: tile
    grid: tile_grid_of_source
    url: http://127.0.0.1/osm_tiles/%(z)s/%(x)s/%(y)s.png

grids:
  tile_grid_of_source:
    base: GLOBAL_MERCATOR
    origin: nw

globals:
  image:
      resampling_method: bicubic

